server:
  port: 7102

eureka:
  client:
    service-url:
      defaultZone: http://yangjn:123456@localhost:8761/eureka/

spring:
  application:
    name: hello-service-provider

logging:
  config: classpath:logback.xml
